const username = 'AndrewDongminYoo';
const repoName = `${username}.vercel`;
const mockName = `${username}/${repoName}`;
const usersApi = `https://api.github.com/users/${username}`;
const reposApi = `https://api.github.com/repos/${mockName}`;
const mockRepository = {
    id: 447431678,
    node_id: 'R_kgDOGqtD_g',
    name: repoName,
    full_name: mockName,
    private: false,
    owner: {
        login: username,
        id: 82999715,
        node_id: 'MDQ6VXNlcjgyOTk5NzE1',
        avatar_url: 'https://avatars.githubusercontent.com/u/82999715?v=4',
        gravatar_id: '',
        url: `${usersApi}`,
        html_url: `https://github.com/${username}`,
        followers_url: `${usersApi}/followers`,
        subscriptions_url: `${usersApi}/subscriptions`,
        organizations_url: `${usersApi}/orgs`,
        repos_url: `${usersApi}/repos`,
        received_events_url: `${usersApi}/received_events`,
        type: 'User',
        site_admin: false,
    },
    html_url: `https://github.com/${mockName}`,
    description: '깃허브 메인 프로필 (+이력서)입니다. NextJS',
    fork: false,
    languages_url: `${reposApi}/languages`,
    created_at: '2022-01-13T02:03:50Z',
    updated_at: '2023-01-18T13:04:10Z',
    pushed_at: '2023-01-18T13:34:47Z',
    svn_url: `https://github.com/${mockName}`,
    homepage: `https://${username}.github.io`,
    size: 35801,
    stargazers_count: 2,
    watchers_count: 2,
    language: 'TypeScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    has_discussions: false,
    forks_count: 0,
    archived: false,
    disabled: false,
    open_issues_count: 1,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: ['nextjs', 'profile', 'react', 'resume', 'tailwindcss'],
    visibility: 'public',
    forks: 0,
    open_issues: 1,
    watchers: 2,
    default_branch: 'main',
    languages: {
        TypeScript: 79630,
        CSS: 11761,
        JavaScript: 6169,
    },
};

export const readRepositories = jest.fn(() => [mockRepository, mockRepository, mockRepository]);
