import {
    faAppStoreIos,
    faAws,
    faBloggerB,
    faCodepen,
    faCss3,
    faDev,
    faDiscord,
    faGitAlt,
    faGithubAlt,
    faGooglePlay,
    faHtml5,
    faJava,
    faJs,
    faMarkdown,
    faNodeJs,
    faNpm,
    faPython,
    faReact,
    faSlack,
    faSquareGit,
    faSquareGithub,
    faSquareJs,
    faYarn,
} from '@fortawesome/free-brands-svg-icons';
import {
    faBlog,
    faCodeFork,
    faEye,
    faLaptopCode,
    faLock,
    faLockOpen,
    faPrint,
    faTerminal,
} from '@fortawesome/free-solid-svg-icons';
import { faCalendarCheck, faIdCard, faStar } from '@fortawesome/free-regular-svg-icons';

export {
    faAppStoreIos,
    faAws,
    faBlog,
    faBloggerB,
    faCalendarCheck,
    faCodeFork,
    faCodepen,
    faCss3,
    faDev,
    faDiscord,
    faEye,
    faGitAlt,
    faGithubAlt,
    faGooglePlay,
    faHtml5,
    faIdCard,
    faJava,
    faJs,
    faLaptopCode,
    faLock,
    faLockOpen,
    faMarkdown,
    faNodeJs,
    faNpm,
    faPrint,
    faPython,
    faReact,
    faSlack,
    faStar,
    faSquareGit,
    faSquareGithub,
    faSquareJs,
    faTerminal,
    faYarn,
};
