rules:
  quoted-strings:
    quote-type: single
    required: only-when-needed
    extra-allowed: ['{|}']
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true
  key-duplicates: {}
  octal-values:
    forbid-implicit-octal: true
ignore:
  - data/posts/experience_*.yaml
